services:
  - type: web
    name: gymhome
    env: node
    region: oregon
    branch: master
    root: GymHome_Demo
    buildCommand: npm ci
    startCommand: npm start
    plan: free

  - type: postgres
    name: gymhome-db
    databaseName: gymhome
    region: oregon
    plan: starter
